### ISSUE TITLE
Is this section in the row poly inference correct?

### ISSUE THREAD

**Issue by 7sharp9** [tomprimozic/type-systems#9]
Hi, Im just querying if this section is correct:

https://github.com/tomprimozic/type-systems/blob/master/extensible_rows/infer.ml#L78-L83
```
		| TRowExtend(label1, field_ty1, rest_row1), (TRowExtend _ as row2) -> begin
				let rest_row1_tvar_ref_option = match rest_row1 with
					| TVar ({contents = Unbound _} as tvar_ref) -> Some tvar_ref
					| _ -> None
				in
				let rest_row2 = rewrite_row row2 label1 field_ty1 in
				begin match rest_row1_tvar_ref_option with
					| Some {contents = Link _} -> error "recursive row types"
					| _ -> ()
				end ;
				unify rest_row1 rest_row2
			end
```

`rest_row1_tvar_ref_option` is `Some` when `contents = Unbound` yet the check to throw on recursion  tests for a `Link` which will never be matched.

**Comment by tomprimozic** [comment]
I think it is, yes. If `rest_row1` is an `Unbound` `TVar`, we want it to remain that way even after we  extract `label1` from `row2`.

To see why, check out [this test case](https://github.com/tomprimozic/type-systems/blob/master/extensible_rows2/test_infer.ml#L95):

    fun r -> choose({x = zero | r}, {y = one | r})

Here, the algorithm starts by typing `r` as `TVar {contents = Unbound _}`. Then it needs to unify both row types, so in the code above, `label1` is `"x"`, `field_ty1` is `TConst "int"`, and `rest_row1` is set to the type of `r`. We then try to extract the field `x` from `row2`, which extends `r` with field `y`, so in `rewrite_row` the algorithm concludes that `r` must have type `{x: int | s}` for some `s`. To avoid infinite recursion when calling `unify` on `rest_row1` and `rest_row2`, we throw an exception now that the type of `r` (i.e. `rest_row1`) is `TVar {contents = Link _}`.

I hope this is clear, please let me know if not.

**Comment by 7sharp9** [comment]
Thanks for the answer, I must be misunderstanding the code somewhere, I understand the premise of the algorithm.

From the code I would say `rest_row1_tvar_ref_option` is always bound to:
 `Some {contents = Unbound _} ` or `None`
 and the recursion check is only matching on `Some {contents = Link _}`.

I could understand if the `rest_row1_tvar_ref_option` was not matching solely on `Unbound` like this :
```
let rest_row1_tvar_ref_option =
    match rest_row1 with
    | TVar ({contents = contents } as tvar_ref) -> Some tvar_ref
    | _ -> None
```
I'll stare at this a little longer though ...

**Comment by 7sharp9** [comment]
The test case you linked was in `extensible_rows2` Im just looking at `extensible_rows` in case we are looking at different projects.  Thanks!

**Comment by tomprimozic** [comment]
Ah, you're right. There is the [same unittest](https://github.com/tomprimozic/type-systems/blob/master/extensible_rows/test_infer.ml#L90) in `extensible_rows` as well.

The `contents` field of a `tvar ref` is mutable - see [OCaml's `ref` type](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html#1_References) and the [definition of the `TVar` variant](https://github.com/tomprimozic/type-systems/blob/master/extensible_rows/expr.ml#L20) - so it's actually mutated in place by the type inference algorithm, that's why it can change between the two `match` statements. This algorithm, called [Union-Find](https://en.wikipedia.org/wiki/Disjoint-set_data_structure), _could_ be implemented in a purely functional way, but implementing it with mutable types _massively_ increases performance.

**Comment by 7sharp9** [comment]
@tomprimozic Thanks for taking the time with the explanation, I think I can see now.  The `TVar` in row2 is being rewritten, and as its the same reference as the one in row one the next match is successful. Staring at the code its not immediately obvious that thats happening unless you think about the intent of the recursion test - to ensure that the extension is not self referencing.  

It would be nice to extend this with variant types too, thanks for this resource its really useful!
